export const ADD_BOARD = 'ADD_BOARD'
export const DELETE_BOARD = 'DELETE_BOARD'
export const CANGE_BOARD_TITLE = 'CANGE_BOARD_TITLE'
export const ADD_CARD = 'ADD_CARD'
export const DELETE_CARD = 'DELETE_CARD'
export const CHANGE_CARD = 'CHANGE_CARD'
export const PREV_BOARD = 'PREV_BOARD'
export const NEXT_BOARD = 'NEXT_BOARD'